### ISSUE TITLE
Mapping or not mapping

### ISSUE THREAD

**Issue by rodesousa** [rodesousa/luz-lantern#4]
Bon @ptavares, faut choisir.

La technique que j'avais mis en place était de mappé correctement le yaml jusqu'au argument:

```
  cmd:
      - user:
          name: aze 
      - user:
          name: lala
      - user:
          name : ippon
      - user:
          name : root 
```

D'ou map[string][]map[string]map[string]interface{}
(le dernier interface nous permet d'avoir en argument soit un array soit une variable)

C'est pour cela que j'avais fait ds un objet Shard un var arg qui a comme type map[string]interface{} pour que dans le mapping on a qu'a faire un :

```
arg = value
```

Sur la dev j'ai mis le code. J'ai pas delete l'ancienne facon (List.list).

On prend quoi ? =)

**Comment by ptavares** [comment]
OK avec ton explication.
On garde ta version et  je comprends mieux le pourquoi tu choix du `Arg_type map[string]interface{}`
Je modifie le code en conséquence.

**Comment by rodesousa** [comment]
Du coup ds le code j'ai mis des balises

```
//
// list.List
//
```

pour cibler ce qu'il faut enlever.Il faut aussi renvoyer un []interface (ou équivalent) qui doit contenir l'ensemble des shards (qui peuvent etre user, ping etc...)

Commit, je fais une review et on merge

**Comment by rodesousa** [comment]
t'as fait list
